spring.application.name=saberpro

# Configuracion del servidor
server.port=8095

# Configuracion H2 Database (En Memoria)
#spring.datasource.url=jdbc:h2:mem:saberprodb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.url=jdbc:postgresql://ep-crimson-wind-ahnlupcd-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_PxpFXGae74Mb
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuracion JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola H2 (para ver la base de datos)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.h2.console.enabled=false

# Configuracion Thymeleaf
spring.thymeleaf.cache=false

# Inicializacion de datos
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
