spring.application.name=saberpro

# Configuracion del servidor
server.port=8095

# Configuracion H2 Database (En Memoria)
#spring.datasource.url=jdbc:h2:mem:saberprodb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.url=jdbc:mysql://ug4umfifumurioow:LXkQQdECZfuNgpEX55tC@bqpbflabga6dqagqlzkl-mysql.services.clever-cloud.com:3306/bqpbflabga6dqagqlzkl
spring.datasource.username=ug4umfifumurioow
spring.datasource.password=LXkQQdECZfuNgpEX55tC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Configuracion JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola H2 (para ver la base de datos)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.h2.console.enabled=false

# Configuracion Thymeleaf
spring.thymeleaf.cache=false

# Inicializacion de datos
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true